### ISSUE TITLE
Action failing on GitHub Enterprise server

### ISSUE THREAD

**Issue by palloberg** [Mozilla-Actions/sccache-action#143]
The action does not work when using GitHub Enterprise Server (GHES) as Octokit's `getLatestRelease` will use the local server API instead of reaching out to GutHub.com for the latest release of `mozilla/sccache` and thus fail.

For this to work on GHES the `baseUrl` must be hardcoded to `https://api.github.com` when calling `getOctokit` in `setup.ts`:
```js
const octokit = getOctokit(token, {baseUrl: 'https://api.github.com'});
```

Users of the action must provide the `token` parameter when calling the action, i.e.:
```yml
      - uses: mozilla-actions/sccache-action@main
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
```

(preferably obtaining the token using https://github.com/actions/create-github-app-token).
