### ISSUE TITLE
[Feature request] Run the statistics generation to annotation at a custom point in the workflow, not at the end

### ISSUE THREAD

**Issue by whisperity** [Mozilla-Actions/sccache-action#183]
## Problem description

I am reporting about an observation related to Mac workflows. Mac workflows are always executed on GitHub SaaS hardware from a set pool, you can not rent Macs from cloud providers or from GitHub directly. Their performance (compared to both standard and the rentable offerings of Linux and Windows machines) is heavily limited.

The workflow file looks like this:

```yaml
steps:
  - uses: actions/checkout
  - name: Install system dependencies...
  - uses: mozilla-actions/sccache-action
  - run: cmake
  - run: ninja
  # POINT 1.
  - run: tests1
  - run: tests2
  - uses: actions/upload-artifact
  - name: Upload artefacts to external cloud provider
  # POINT 2.
```

Here, `tests1`, `tests2`, etc., are long-running; and `Upload artefacts to external cloud provider` are flakily long-running operations. What I observed is that at `POINT 2` (where the automatic statistics printing, by default, takes place), in some cases, the `sccache` server is dead. My hypothesis is that it is killed by something equivalent to an OOM-killer (MacOS workers only get 7 GiB of RAM!).

The `tests` jobs or anything following the `ninja` build system call do **not** use `sccache` at all.

## Observed behaviour

At the end of the workflow, when `sccache --show-stats` is executed by the Action, a report of 0 cache actions and 0 cache use is created, and `sccache` behaves as if it was using the **local** cache. Normally, the build is using a cache via an external cloud provider plugin, and the use of this is verified to be the case because we start the server with logging and archive the `sccache.log` file. In it, the access and the successful cache writes following cache misses are apparent.

![Rendered sccache stats showing 0s everywhere](https://github.com/user-attachments/assets/f111cccb-04ca-463a-9cae-7d82f0d482c7)

![sccache stats in the command-line showing that it is querying statistics for the local cache (that is not used)](https://github.com/user-attachments/assets/21194078-0da1-4b84-b55f-885f6ce33c81)

This makes the "Post action" statistics printing essentially useless and misleading.

**However**, if I manually insert a `run: sccache --show-stats` at **`POINT 1`**, then I get the right statistics output. In case I run a lighter workflow by skipping some of the tests and happening to "hit the jackpot" with the `Upload artefacts to external cloud provider` succeeding on the first try instead of several retries (all in all contributing to lowering the chances of `sccache` becoming OOM-killed), then at `POINT 2` the `sccache` process is still alive, and the automatic statistics reporting happens with the proper useful values.

Something in this nature:

```yaml
steps:
  - uses: actions/checkout
  - name: Install system dependencies...
  - uses: mozilla-actions/sccache-action
    with:
      disable_annotations: true
  - run: cmake
  - run: ninja
  - uses: mozilla-actions/sccache-action
    with:
      only_report_annotations: true
  - run: tests1
  - run: tests2
  - uses: actions/upload-artifact
  - name: Upload artefacts to external cloud provider
```

or

```yaml
steps:
  - uses: actions/checkout
  - name: Install system dependencies...
  - uses: mozilla-actions/sccache-action
    with:
      disable_annotations: true
  - run: cmake
  - run: ninja
  - run: $(dirname $SCCACHE_PATH)/stats-to-github.sh
  - run: tests1
  - run: tests2
  - uses: actions/upload-artifact
  - name: Upload artefacts to external cloud provider
```

![sccache --show-stats executed manually right after the build (after the last point sccache is actually used in the workflow) showing that the server is still alive and was able to report the ACTUAL statistics for the actual third-party cloud cache used during the build](https://github.com/user-attachments/assets/7722e8f0-4ad0-4626-bd82-ab7d195c60fe)

## Considered alternatives

Although it would be possible theoretically to set up a pipeline of jobs where the "build" is a dedicated step which could report the proper statistics accurately and in a timely manner prior to running the next job which runs the tests and archives artefacts, there are two problems with that approach:

1. the actual project under question is the LLVM Project, which has insane compilation and linking times (even if the cache is hot (almost 10 minutes!), but definitely when the cache is cold (1 hr 40 mins!)) and binary sizes (somewhere around 20 or so GiB)
2. on GitHub Actions, the communication of resources between workflows is only possible via artefacts… but one of the major contributors of the OOM problems observed is the long-running nature of the artefact upload routine, which makes this a self-cyclic problem
