### ISSUE TITLE
Cache writes failing on version 0.0.8

### ISSUE THREAD

**Issue by moechaieb** [Mozilla-Actions/sccache-action#191]
Hey everyone,

I have been using sccache for a while now, and since I upgraded to `0.0.8` I started seeing the following in my build's sccache summary:

```
Compile requests                    488
Compile requests executed           488
Cache hits                            0
Cache misses                        488
Cache misses (C/C++)                488
Cache hits rate                    0.00 %
Cache hits rate (C/C++)            0.00 %
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                  488
Cache errors                          0
Compilations                        488
Compilation failures                  0
Non-cacheable compilations            0
Non-cacheable calls                   0
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average compiler                  4.444 s
Average cache read hit            0.000 s
Failed distributed compilations       0
Cache location                  ghac, name: sccache-v0.10.0, prefix: /sccache/
Version (client)                0.10.0
```

This was consistent from build to build, across both `macos-latest` and `windows-latest` runners.

After enabling debug logging, the underlying error I could see was:

```
2025-03-24T11:17:57.8556910Z [2025-03-24T11:05:40Z DEBUG sccache::server] Error executing cache write: Cannot write to read-only storage
```

The number of times this error is logged corresponds exactly to the number of cache write errors, so I think it's safe to attribute this issue to this error.

Note that my configuration is vanilla:

```yaml
      - name: Cache CMake build
        uses: mozilla-actions/sccache-action@v0.0.7
```

With the following env variables set:

```env
SCCACHE_GHA_ENABLED: true
SCCACHE_CACHE_MULTIARCH: 1
```

I then proceed to build my targets with multiple `cmake` commands (grouping all my targets makes the build fail for another, unrelated reason):

```yaml
      # Steps to build the required targets
      - name: CMake build (macOS)
        if: startsWith(runner.os, 'macos') && steps.skip_build.outputs.skip != 'true'
        run: |
          cmake -B ${{ env.BUILD_DIR }} -G Ninja -DCMAKE_BUILD_TYPE=${{ env.PLUGIN_RELEASE_TYPE}} -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DJUCE_COPY_PLUGIN_AFTER_BUILD=ON .
          cmake --build ${{ env.BUILD_DIR }} --config ${{ env.PLUGIN_RELEASE_TYPE }} --target ${{matrix.os.build_targets}} --parallel 4
```

Could you guys help investigate why this is happening in `0.0.8` and not `0.0.7`?

I have attached the debug logs from version 0.0.8 (failing), and 0.0.7 (working).

[sccache-0.0.7.log](https://github.com/user-attachments/files/19429140/sccache-0.0.7.log)
[sccache-0-0-8.log](https://github.com/user-attachments/files/19429141/sccache-0-0-8.log)
