### ISSUE TITLE
Tons of rate limit errors

### ISSUE THREAD

**Issue by yujincheng08** [Mozilla-Actions/sccache-action#50]
I found that my action's cache hit rate is too low (especially for c/c++). I enable debug log and saw tons of rate limits. How to solve this?

```
data close failed: RateLimited (temporary) at Writer::close => ﻿{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace ''.","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}
```

**Comment by yujincheng08** [comment]
FYI, the first build:
https://github.com/LSPosed/Metagisk/actions/runs/5209660209/attempts/1

And the second build (re-trigger):
https://github.com/LSPosed/Metagisk/actions/runs/5209660209

And there are 1440 C/C++ misses!

Here you are the log from the first build, and you can see there are tons of rate limits after a specific step.

[sccache_log.zip](https://github.com/Mozilla-Actions/sccache-action/files/11686927/sccache_log.zip)

That drastically drops the hit rate of the second build.

**Comment by Xuanwo** [comment]
There are very little thing we can do for this. Sccache & Ghac are designed like this: too much small object will lead to rate limit.

Try setup a s3 bucket if the speed is critical to you.

**Comment by yujincheng08** [comment]
Ok. Then I will use sccache locally and then upload to GitHub action cache like I previously do.

**Comment by Xuanwo** [comment]
https://github.com/topjohnwu/Magisk/pull/7052 seems a nice idea! We can add this feature in `sccache-action` too.

**Comment by sylvestre** [comment]
@Xuanwo is that something you could implement ? :)

**Comment by sylvestre** [comment]
See https://github.com/mozilla/sccache/pull/1818 & https://github.com/orgs/community/discussions/55049

**Comment by mwestphal** [comment]
In order to work around this, I had to implement my own sccache logic and not rely on this action, here it is if it helps anyone:


```
  - name: Initialize sccache environnement
    shell: bash
    run: |
      echo SCCACHE_CACHE=$(sccache --show-stats | grep Local | cut -d '"' -f2) >> $GITHUB_ENV
      echo DATE_STRING=$(date +'%Y%m%d') >> $GITHUB_ENV
      sccache --stop-server

  - name: Recover sccache cache
    uses: actions/cache@v3
    with:
      path: ${{env.SCCACHE_CACHE}}
      key: sccache-cache-${{runner.os}}-0-${{env.DATE_STRING}}
      restore-keys: sccache-cache-${{runner.os}}-0

  - name: Start sccache
    shell: bash
    working-directory: ${{github.workspace}}
    run: sccache --start-server

[...]    

  - name: Cleanup sccache
    working-directory: ${{github.workspace}}
    shell: bash
    run: sccache --stop-server
```

 - First step run the server, recover cache location and current data, then stop the server
 - Second step recover a github action cache based on the `runner.os` AND the date. If the cache for today has not been created, it will grab the cache from yesterday thanks to the `restore-key` logic. A single cache file is used, not hundreds.
 - Third step start the server
 - Last step stop the server and report stats
 - On cleanup, cache action upload today's cache if it was not available
 
 A 2h C++ build now takes less than 1 hour.
 
 Hth,
