### ISSUE TITLE
Suggestions about cache handling

### ISSUE THREAD

**Issue by mwestphal** [Mozilla-Actions/sccache-action#70]
I tried using this action in my project but the performance are not at all what I expected.

Here is what I get:

```
Compile requests                   9129
Compile requests executed          9129
Cache hits                         6531
Cache hits (C/C++)                 6531
Cache misses                       2598
Cache misses (C/C++)               2598
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   0
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.026 s
Average compiler                  4.729 s
Average cache read hit            0.034 s
Failed distributed compilations       0
Cache location                  ghac, name: sccache-v0.5.4, prefix: /sccache/
Version (client)                0.5.4
```

Although when I set up sccache with github cache myself, I get this:

```
Compile requests                   9122
Compile requests executed          9122
Cache hits                         9113
Cache hits (C/C++)                 9113
Cache misses                          9
Cache misses (C/C++)                  9
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   0
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average compiler                  2.476 s
Average cache read hit            0.000 s
Failed distributed compilations       0
Cache location                  Local disk: "/github/home/.cache/sccache"
Version (client)                0.4.2
Cache size                          207 MiB
Max cache size                       10 GiB
```

I think this is related to the fact than I'm using a single cache file insead of hundreds as you seem to be doing.

The logic I'm using is that the cache file name contains the date of the build, like this:

```
  - name: Initialize sccache environnement
    shell: bash
    run: |
      echo SCCACHE_CACHE=$(sccache --show-stats | grep Local | cut -d '"' -f2) >> $GITHUB_ENV
      echo DATE_STRING=$(date +'%Y%m%d') >> $GITHUB_ENV
      sccache --stop-server

  - name: Recover sccache cache
    uses: actions/cache@v3
    with:
      path: ${{env.SCCACHE_CACHE}}
      key: sccache-cache-${{inputs.raytracing_label}}-${{runner.os}}-0-${{env.DATE_STRING}}
      restore-keys: sccache-cache-${{inputs.raytracing_label}}-${{runner.os}}-0
```

This means the cache is being updated everyday, and it avoids using hundreds of caches.
